/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stackjava.com.filtermailspam;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;

import java.util.Scanner;


/**
 *
 * @author Phạm T.Vi
 */
public class ChiTietLoc extends javax.swing.JFrame {
        JFileChooser file ;
         File f;
          public  static String tenCanHuanLuyen;
        //tạo danh sach listModel nospam
         DefaultListModel<String> modelNospam = new DefaultListModel<>();
         DefaultListModel<String> modelspam = new DefaultListModel<>();
	// mảng chứa các túi từ của thư thường (non-spam)
	static ArrayList<Set<String>> listBagOfNonSpam = new ArrayList<>();
	// mảng chứa các túi từ của thư rác (spam)
	static ArrayList<Set<String>> listBagOfSpam = new ArrayList<>();
    /**
     * Creates new form GiaoDien
     */
    public ChiTietLoc() {
        initComponents();
    }
    // tinh xac xuat P(xi=x|nhan= nonspam)
	public static double pNonSpam(String x) { 
		double k = 0;
		for (int i = 0; i < listBagOfNonSpam.size(); i++) {
			// moi lan x xuat hien trong 1 thu thuong thi k++
			if (listBagOfNonSpam.get(i).contains(x))
				k++;
		}
		return (k + 1) / (listBagOfNonSpam.size() + 1);
		// P(xi|nhan= nonspam)= (k+1)/(sothuthuong+1);
		// trong do: k la so cac mail nonspam xuat hien xi
		// sothuthuong la so mail nonspam

	}

	// tinh xac xuat P(xi=x|nhan= spam)
	public static double pSpam(String x) {
		double k = 0;
		for (int i = 0; i < listBagOfSpam.size(); i++) {
			if (listBagOfSpam.get(i).contains(x))
				// moi lan x xuat hien trong 1 thu rac thi k++
				k++;
		}
		return (k + 1) / (listBagOfSpam.size() + 1);
		// P(xi|nhan= spam)= (k+1)/(sothurac+1);
		// trong do: k la so cac mail spam xuat hien xi
		// sothurac la so mail spam
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListNospam = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listspam = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jcomMauNen = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcMauChu = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcSizeChu = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_NoiDungFile = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        txt_SSKQ = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stackjava/com/filtermailspam/MoFile.png"))); // NOI18N
        jButton1.setText("File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/_result_training/Loc.png"))); // NOI18N
        jButton2.setText("Xử lý");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CHI TIẾT LỌC THƯ RÁC");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Nospam", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        jScrollPane1.setViewportView(ListNospam);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Spam", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        jScrollPane2.setViewportView(listspam);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đổi không khí", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(204, 0, 0))); // NOI18N

        jcomMauNen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trắng", "Vàng", "Hồng", "Da cam", "Đen" }));
        jcomMauNen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomMauNenActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Màu nền:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Màu chữ");

        jcMauChu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trắng", "Vàng", "Hồng", "Da cam", "Đen" }));
        jcMauChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMauChuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Size chữ: ");

        jcSizeChu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Size 14", "Size 15", "Size 16", "Size 17", "Size 18" }));
        jcSizeChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcSizeChuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcomMauNen, 0, 107, Short.MAX_VALUE)
                    .addComponent(jcMauChu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcSizeChu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomMauNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcMauChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcSizeChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7))
        );

        txt_NoiDungFile.setColumns(20);
        txt_NoiDungFile.setRows(5);
        jScrollPane3.setViewportView(txt_NoiDungFile);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kết quả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(153, 0, 0))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(txt_SSKQ, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_SSKQ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(27, 27, 27)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         file = new JFileChooser();
        FileNameExtensionFilter imgFile = new FileNameExtensionFilter("jpg","png","mp4","rar","txt", "doc", "raa");
        file.setFileFilter(imgFile);
        file.setMultiSelectionEnabled(false);//fasle là chọn 1 file
        int x = file.showDialog(this, "Chọn file");
        if (x == JFileChooser.APPROVE_OPTION) {//file đc chọn
             f = file.getSelectedFile();
            ImageIcon t = new ImageIcon(f.getName());
            tenCanHuanLuyen = "data/test/"+t.getDescription().toString()+"";
        }
    }//GEN-LAST:event_jButton1ActionPerformed
      public  void xuLy()throws FileNotFoundException, IOException, ClassNotFoundException {
            // đọc dữ liệu huấn luyện từ trước ở trong file result_training.dat ra
		System.out.println("Bắt đầu load dữ liệu huấn luyện");
		ObjectInputStream inp = new ObjectInputStream(
				new FileInputStream(new File("data/_result_training/result_training.dat")));
		listBagOfSpam = (ArrayList<Set<String>>) inp.readObject();
		listBagOfNonSpam = (ArrayList<Set<String>>) inp.readObject();
		inp.close();
		System.out.println("Hoàn load dữ liệu huấn luyện");

		// đọc dữ liệu từ mail cần kiểm tra
		System.out.println("Đọc dữ liệu mail cần kiểm tra");
		File mailTesting = new File(tenCanHuanLuyen.toString());
		// Tiền xử lý mail cần kiểm tra

		String mailData = FileUtils.readFileToString(mailTesting, "UTF-8");
		Set<String> bagOfTest = RunTrainingData.toBagOfWord(mailData);

		System.out.println("Bắt đầu kiểm tra:");

		// xác xuất là thư thường. P(xi|non-spam)
		double C_NB1 = listBagOfNonSpam.size() / ((double) listBagOfNonSpam.size() + listBagOfSpam.size());
		// xác xuất là thư rác. P(xi|spam)
		double C_NB2 = listBagOfSpam.size() / ((double) listBagOfNonSpam.size() + listBagOfSpam.size());

		ArrayList<String> listStringTest = new ArrayList<>(bagOfTest);

		for (String strTest : listStringTest) {
			if (pNonSpam(strTest) != ((double) 1 / (listBagOfNonSpam.size() + 1))
					|| pSpam(strTest) != ((double) 1 / (listBagOfSpam.size() + 1))) {
                              //Bỏ vào ListModel nospam
                               modelNospam.addElement("P(x_i=" + strTest+ "|nospam)= "+ pNonSpam(strTest) +"");
                                ListNospam.setModel(modelNospam);
                              //Bỏ vào ListModel spam
                              modelspam.addElement("P(x_i=" + strTest+ "|spam)= "+pSpam(strTest) +"");
                              listspam.setModel(modelspam);
                              //Xuất dưới màng hinnh
				System.out.println("P(x_i=" + strTest + "|nonspam)=  " + pNonSpam(strTest) + "        " + "P(x_i="
						+ strTest + "|spam)=  " + pSpam(strTest));
                                
				C_NB1 *= pNonSpam(strTest);
				C_NB2 *= pSpam(strTest);   
			}
                        
		}
		if (C_NB1 < C_NB2) {
			// Bổ sung thư vừa kiểm tra vào tập huấn luyện.
			listBagOfSpam.add(bagOfTest);
			System.out.println("Là thư rác");
                        jTextField3.setText("Là thư rác");
                          txt_SSKQ.setText(""+C_NB1+" < "+C_NB2+"");
		} else {
			listBagOfNonSpam.add(bagOfTest);
			System.out.println("Là thư thường");
                        jTextField3.setText("Là thư thường") ;
                        txt_SSKQ.setText(""+C_NB1+" > "+C_NB2+"");
		}
                 
		// Lưu lại tập huấn luyện mới.
		ObjectOutputStream out = new ObjectOutputStream(
				new FileOutputStream(new File("data/_result_training/result_training.dat")));
		out.writeObject(listBagOfSpam);
		out.writeObject(listBagOfNonSpam);
		out.close();
		System.out.println("Kết thúc");
        }
      
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            xuLy();
        } catch (IOException ex) {
            Logger.getLogger(ChiTietLoc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ChiTietLoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader br = null;

        try {   
            br = new BufferedReader(new FileReader("C:\\Users\\Admin\\Documents\\DA_KhaiThac\\DoAn\\LocThuRac_KTDL\\JavaApplication6\\"+tenCanHuanLuyen.toString()+""));       
            int num=0;
            char ch;
            String s="";
            while((num = br.read()) != -1)
            {    
                ch = (char) num;
                s +=""+ch+"";
            }
            txt_NoiDungFile.setText(s);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                br.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcomMauNenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomMauNenActionPerformed
        // TODO add your handling code here:
        int n = jcomMauNen.getSelectedIndex();
        if(n == 0){
            listspam.setBackground(Color.white);
            ListNospam.setBackground(Color.white);
        }
        if(n == 1){
            listspam.setBackground(Color.YELLOW);
             ListNospam.setBackground(Color.YELLOW);
        }
        if(n == 2){
            listspam.setBackground(Color.PINK);
             ListNospam.setBackground(Color.PINK);
        }
        if(n == 3){
            listspam.setBackground(Color.ORANGE);
             ListNospam.setBackground(Color.ORANGE);
        }
        if(n == 4){
            listspam.setBackground(Color.black);
             ListNospam.setBackground(Color.black);
        }
    }//GEN-LAST:event_jcomMauNenActionPerformed

    private void jcMauChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMauChuActionPerformed
        // TODO add your handling code here:
        int n = jcMauChu.getSelectedIndex();
        if(n == 0){
            listspam.setForeground(Color.white);
            ListNospam.setForeground(Color.white);
        }
        if(n == 1){
            listspam.setForeground(Color.YELLOW);
             ListNospam.setForeground(Color.YELLOW);
        }
        if(n == 2){
            listspam.setForeground(Color.PINK);
             ListNospam.setForeground(Color.PINK);
        }
        if(n == 3){
            listspam.setForeground(Color.ORANGE);
             ListNospam.setForeground(Color.ORANGE);
        }
        if(n == 4){
            listspam.setForeground(Color.black);
             ListNospam.setForeground(Color.black);
        }
    }//GEN-LAST:event_jcMauChuActionPerformed

    private void jcSizeChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcSizeChuActionPerformed
        // TODO add your handling code here:
        int n = jcMauChu.getSelectedIndex();
        if(n == 0){
            listspam.setFont(new Font("Times New Roman" , Font.BOLD, 14));
            ListNospam.setFont(new Font("Times New Roman" , Font.BOLD, 14));
        }
        if(n == 1){
            listspam.setFont(new Font("Times New Roman" , Font.BOLD, 15));
              ListNospam.setFont(new Font("Times New Roman" , Font.BOLD, 15));
        }
        if(n == 2){
            listspam.setFont(new Font("Times New Roman" , Font.BOLD, 16));
              ListNospam.setFont(new Font("Times New Roman" , Font.BOLD, 16));
        }
        if(n == 3){
            listspam.setFont(new Font("Times New Roman" , Font.BOLD, 17));
              ListNospam.setFont(new Font("Times New Roman" , Font.BOLD, 17));
        }
        if(n == 4){
            listspam.setFont(new Font("Times New Roman" , Font.BOLD, 18));
              ListNospam.setFont(new Font("Times New Roman" , Font.BOLD, 18));
        }
    }//GEN-LAST:event_jcSizeChuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DAO d = new DAO();
        d.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietLoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListNospam;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> jcMauChu;
    private javax.swing.JComboBox<String> jcSizeChu;
    private javax.swing.JComboBox<String> jcomMauNen;
    private javax.swing.JList<String> listspam;
    private javax.swing.JTextArea txt_NoiDungFile;
    private javax.swing.JTextField txt_SSKQ;
    // End of variables declaration//GEN-END:variables
}
