package stackjava.com.filtermailspam;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import org.apache.commons.io.FileUtils;
/**
 *
 * @author Admin
 */
public class DAO extends javax.swing.JFrame {

    double C_NB1;
    double C_NB2 ;
    String s;
    /**
     * Creates new form DAO
     */
    public DAO() {
        initComponents();
    }
    // mảng chứa các túi từ của thư thường (non-spam)
	static ArrayList<Set<String>> listBagOfNonSpam = new ArrayList<>();
	// mảng chứa các túi từ của thư rác (spam)
	static ArrayList<Set<String>> listBagOfSpam = new ArrayList<>();
        
       //tạo danh sach listModel nospam
         DefaultListModel<String> modelNospam = new DefaultListModel<>();
         DefaultListModel<String> modelspam = new DefaultListModel<>();
        DefaultListModel<String> f = new DefaultListModel<>();
        
  
	// tinh xac xuat P(xi=x|nhan= nonspam)
	public static double pNonSpam(String x) { 
		double k = 0;
		for (int i = 0; i < listBagOfNonSpam.size(); i++) {
			// moi lan x xuat hien trong 1 thu thuong thi k++
			if (listBagOfNonSpam.get(i).contains(x))
				k++;
		}
		return (k + 1) / (listBagOfNonSpam.size() + 1);
		// P(xi|nhan= nonspam)= (k+1)/(sothuthuong+1);
		// trong do: k la so cac mail nonspam xuat hien xi
		// sothuthuong la so mail nonspam

	}

	// tinh xac xuat P(xi=x|nhan= spam)
	public static double pSpam(String x) {
		double k = 0;
		for (int i = 0; i < listBagOfSpam.size(); i++) {
			if (listBagOfSpam.get(i).contains(x))
				// moi lan x xuat hien trong 1 thu rac thi k++
				k++;
		}
		return (k + 1) / (listBagOfSpam.size() + 1);
		// P(xi|nhan= spam)= (k+1)/(sothurac+1);
		// trong do: k la so cac mail spam xuat hien xi
		// sothurac la so mail spam
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtfile = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jcomMauNen = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcMauChu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jcSizeChu = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listspam = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListNospam = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LỌC THƯ RÁC SPAM");

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/_result_training/Loc.png"))); // NOI18N
        jButton1.setText("Lọc Dữ Liệu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtfile.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                txtfileValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(txtfile);

        jButton2.setBackground(new java.awt.Color(0, 255, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/_result_training/DuLiu.png"))); // NOI18N
        jButton2.setText("Hiển thị dữ liệu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/_result_training/Chitiet.png"))); // NOI18N
        jButton3.setText("Chi tiết lọc thư");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đổi không khí", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(204, 0, 0))); // NOI18N

        jcomMauNen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trắng", "Vàng", "Hồng", "Da cam", "Đen" }));
        jcomMauNen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomMauNenActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Màu nền:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Màu chữ");

        jcMauChu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trắng", "Vàng", "Hồng", "Da cam", "Đen" }));
        jcMauChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMauChuActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Size chữ: ");

        jcSizeChu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Size 14", "Size 15", "Size 16", "Size 17", "Size 18" }));
        jcSizeChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcSizeChuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcomMauNen, 0, 107, Short.MAX_VALUE)
                    .addComponent(jcMauChu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcSizeChu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomMauNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcMauChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcSizeChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Spam", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        jScrollPane4.setViewportView(listspam);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Nospam", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        jScrollPane1.setViewportView(ListNospam);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon("D:\\DoAn\\LocThuRac_KTDL\\JavaApplication6\\ThemFile.png")); // NOI18N
        jButton4.setText("Thêm File txt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jButton4)
                                .addGap(56, 56, 56)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public  void xuLy()throws FileNotFoundException, IOException, ClassNotFoundException {
          File folder1 = new File("C:\\Users\\Admin\\Documents\\DA_KhaiThac\\DoAn\\LocThuRac_KTDL\\JavaApplication6\\data\\test");
                 File[] listOfFiles = folder1.listFiles();
                for (File file : listOfFiles) {
                   if (file.isFile()) {
            // đọc dữ liệu huấn luyện từ trước ở trong file result_training.dat ra
		System.out.println("Bắt đầu load dữ liệu huấn luyện");
		ObjectInputStream inp = new ObjectInputStream(
				new FileInputStream(new File("data/_result_training/result_training.dat")));
		listBagOfSpam = (ArrayList<Set<String>>) inp.readObject();
		listBagOfNonSpam = (ArrayList<Set<String>>) inp.readObject();
		inp.close();
		System.out.println("Hoàn load dữ liệu huấn luyện");

		// đọc dữ liệu từ mail cần kiểm tra
		System.out.println("Đọc dữ liệu mail cần kiểm tra");
		File mailTesting = new File("data/test/"+file.getName()+"");
		// Tiền xử lý mail cần kiểm tra

		String mailData = FileUtils.readFileToString(mailTesting, "UTF-8");
		Set<String> bagOfTest = RunTrainingData.toBagOfWord(mailData);

		System.out.println("Bắt đầu kiểm tra:");

		// xác xuất là thư thường. P(xi|non-spam)
		double C_NB1 = listBagOfNonSpam.size() / ((double) listBagOfNonSpam.size() + listBagOfSpam.size());
		// xác xuất là thư rác. P(xi|spam)
		double C_NB2 = listBagOfSpam.size() / ((double) listBagOfNonSpam.size() + listBagOfSpam.size());

		ArrayList<String> listStringTest = new ArrayList<>(bagOfTest);

		for (String strTest : listStringTest) {
			if (pNonSpam(strTest) != ((double) 1 / (listBagOfNonSpam.size() + 1))
					|| pSpam(strTest) != ((double) 1 / (listBagOfSpam.size() + 1))) {
                              //Xuất dưới màng hinnh
				System.out.println("P(x_i=" + strTest + "|nonspam)=  " + pNonSpam(strTest) + "        " + "P(x_i="
						+ strTest + "|spam)=  " + pSpam(strTest));
                                
				C_NB1 *= pNonSpam(strTest);
				C_NB2 *= pSpam(strTest);   
			}
                        
		}
		if (C_NB1 < C_NB2) {
			// Bổ sung thư vừa kiểm tra vào tập huấn luyện.
			listBagOfSpam.add(bagOfTest);
			System.out.println("Là thư rác");
                        modelspam.addElement(file.getName());
                        listspam.setModel(modelspam);
                      
		} else {
			listBagOfNonSpam.add(bagOfTest);
			System.out.println("Là thường");
                        modelNospam.addElement(file.getName());
                       ListNospam.setModel(modelNospam);
                      
		}

		// Lưu lại tập huấn luyện mới.
		ObjectOutputStream out = new ObjectOutputStream(
				new FileOutputStream(new File("data/_result_training/result_training.dat")));
		out.writeObject(listBagOfSpam);
		out.writeObject(listBagOfNonSpam);
		out.close();
		System.out.println("Kết thúc");
                   }
                }
        }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        xuLy();
        } catch (IOException ex) {
            Logger.getLogger(DAO.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DAO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtfileValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_txtfileValueChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtfileValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        File folder = new File("C:\\Users\\Admin\\Documents\\DA_KhaiThac\\DoAn\\LocThuRac_KTDL\\JavaApplication6\\data\\test");
            File[] listOfFiles = folder.listFiles();
            
            for (File file : listOfFiles) {
                if (file.isFile()) {
                     f.addElement(file.getName());
                        txtfile.setModel(f);    
                            }
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ChiTietLoc ct = new ChiTietLoc();
        ct.setVisible(true);
        ct.tenCanHuanLuyen = "data/test/"+txtfile.getSelectedValue().toString()+"";
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jcomMauNenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomMauNenActionPerformed
        // TODO add your handling code here:
        int n = jcomMauNen.getSelectedIndex();
        if(n == 0){
            listspam.setBackground(Color.white);
            ListNospam.setBackground(Color.white);
        }
        if(n == 1){
            listspam.setBackground(Color.YELLOW);
            ListNospam.setBackground(Color.YELLOW);
        }
        if(n == 2){
            listspam.setBackground(Color.PINK);
            ListNospam.setBackground(Color.PINK);
        }
        if(n == 3){
            listspam.setBackground(Color.ORANGE);
            ListNospam.setBackground(Color.ORANGE);
        }
        if(n == 4){
            listspam.setBackground(Color.black);
            ListNospam.setBackground(Color.black);
        }
    }//GEN-LAST:event_jcomMauNenActionPerformed

    private void jcMauChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMauChuActionPerformed
        // TODO add your handling code here:
        int n = jcMauChu.getSelectedIndex();
        if(n == 0){
            listspam.setForeground(Color.white);
            ListNospam.setForeground(Color.white);
        }
        if(n == 1){
            listspam.setForeground(Color.YELLOW);
            ListNospam.setForeground(Color.YELLOW);
        }
        if(n == 2){
            listspam.setForeground(Color.PINK);
            ListNospam.setForeground(Color.PINK);
        }
        if(n == 3){
            listspam.setForeground(Color.ORANGE);
            ListNospam.setForeground(Color.ORANGE);
        }
        if(n == 4){
            listspam.setForeground(Color.black);
            ListNospam.setForeground(Color.black);
        }
    }//GEN-LAST:event_jcMauChuActionPerformed

    private void jcSizeChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcSizeChuActionPerformed
        // TODO add your handling code here:
        int n = jcMauChu.getSelectedIndex();
        if(n == 0){
            listspam.setFont(new Font("Times New Roman" , Font.BOLD, 14));
            ListNospam.setFont(new Font("Times New Roman" , Font.BOLD, 14));
        }
        if(n == 1){
            listspam.setFont(new Font("Times New Roman" , Font.BOLD, 15));
            ListNospam.setFont(new Font("Times New Roman" , Font.BOLD, 15));
        }
        if(n == 2){
            listspam.setFont(new Font("Times New Roman" , Font.BOLD, 16));
            ListNospam.setFont(new Font("Times New Roman" , Font.BOLD, 16));
        }
        if(n == 3){
            listspam.setFont(new Font("Times New Roman" , Font.BOLD, 17));
            ListNospam.setFont(new Font("Times New Roman" , Font.BOLD, 17));
        }
        if(n == 4){
            listspam.setFont(new Font("Times New Roman" , Font.BOLD, 18));
            ListNospam.setFont(new Font("Times New Roman" , Font.BOLD, 18));
        }
    }//GEN-LAST:event_jcSizeChuActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ThemFile t = new ThemFile();
        t.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DAO().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListNospam;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> jcMauChu;
    private javax.swing.JComboBox<String> jcSizeChu;
    private javax.swing.JComboBox<String> jcomMauNen;
    private javax.swing.JList<String> listspam;
    private javax.swing.JList<String> txtfile;
    // End of variables declaration//GEN-END:variables
}
